# Generated by Django 4.1.7 on 2023-04-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Eventos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "local",
                    models.CharField(max_length=255, verbose_name="Local do Evento"),
                ),
                (
                    "data_hora",
                    models.DateTimeField(verbose_name="Data e Hora do Evento"),
                ),
                (
                    "max_pessoas",
                    models.IntegerField(default=0, verbose_name="Máximo de pessoas"),
                ),
                (
                    "data_hora_limite",
                    models.DateTimeField(
                        verbose_name="Data e hora limite para inscrição"
                    ),
                ),
            ],
        ),
    ]
