# Generated by Django 4.1.7 on 2023-04-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participantes", "0002_participantes_evento"),
        ("eventos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventos",
            name="inscritos",
            field=models.ManyToManyField(to="participantes.participantes"),
        ),
    ]
