# Generated by Django 4.1.7 on 2023-04-02 02:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("eventos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Participante",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=50, verbose_name="Nome")),
                ("email", models.CharField(max_length=100, verbose_name="E-mail")),
                ("telefone", models.CharField(max_length=11, verbose_name="Celular")),
                (
                    "documento",
                    models.CharField(max_length=11, verbose_name="Documento"),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eventos.evento",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
