# Generated by Django 4.1.7 on 2023-04-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Participantes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, verbose_name="Nome")),
                ("email", models.CharField(max_length=100, verbose_name="E-mail")),
                ("telefone", models.CharField(max_length=11, verbose_name="Celular")),
                (
                    "documento",
                    models.CharField(max_length=11, verbose_name="Documento"),
                ),
            ],
        ),
    ]
