# Generated by Django 4.1.7 on 2023-04-01 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0001_initial"),
        ("participantes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="participantes",
            name="evento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="eventos.eventos",
            ),
        ),
    ]
