# Generated by Django 4.1.7 on 2023-04-02 02:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0002_alter_evento_id"),
        ("participantes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participante",
            name="evento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participantes",
                to="eventos.evento",
            ),
        ),
        migrations.AlterField(
            model_name="participante",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
